"""Removed unique tag for titles for content, question and quiz

Revision ID: 0cd365d17cd8
Revises: e347504aa161
Create Date: 2021-05-17 10:52:46.045150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cd365d17cd8'
down_revision = 'e347504aa161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_index('ix_content_title')
        batch_op.create_index(batch_op.f('ix_content_title'), ['title'], unique=False)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index('ix_question_question')
        batch_op.create_index(batch_op.f('ix_question_question'), ['question'], unique=False)

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_index('ix_quiz_title')
        batch_op.create_index(batch_op.f('ix_quiz_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_title'))
        batch_op.create_index('ix_quiz_title', ['title'], unique=1)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_question'))
        batch_op.create_index('ix_question_question', ['question'], unique=1)

    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_title'))
        batch_op.create_index('ix_content_title', ['title'], unique=1)

    # ### end Alembic commands ###
