"""empty message

Revision ID: 267e6e479b2d
Revises: 39dec6058515
Create Date: 2021-05-07 20:14:32.787808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267e6e479b2d'
down_revision = '39dec6058515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_content_title', table_name='content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_content_title', 'content', ['title'], unique=1)
    # ### end Alembic commands ###
