"""empty message

Revision ID: 39dec6058515
Revises: c29309002efa
Create Date: 2021-05-06 01:08:35.977734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39dec6058515'
down_revision = 'c29309002efa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_title'), 'course', ['title'], unique=True)
    op.alter_column('user', 'admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_course_title'), table_name='course')
    op.drop_table('course')
    # ### end Alembic commands ###
