"""Database update

Revision ID: 77b4b6ae646d
Revises: ed279c7f2160
Create Date: 2021-05-12 08:39:04.816417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b4b6ae646d'
down_revision = 'ed279c7f2160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content__viewed',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('viewed', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question__response',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('response', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('answer')
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('question', sa.String(length=256), nullable=True))
        batch_op.drop_column('body')
        batch_op.drop_column('user_responce')

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('title')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_responce', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('body', sa.VARCHAR(length=140), nullable=True))
        batch_op.drop_column('question')
        batch_op.drop_column('answer')

    op.create_table('answer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question_id', sa.INTEGER(), nullable=True),
    sa.Column('answer', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('question__response')
    op.drop_table('content__viewed')
    # ### end Alembic commands ###
