"""Cascading Delete for User

Revision ID: b5eb7560c6f4
Revises: 98519a88d44a
Create Date: 2021-05-17 16:38:32.639223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5eb7560c6f4'
down_revision = '98519a88d44a'
branch_labels = None
depends_on = None

naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content__viewed', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint('fk_content__viewed_user_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_content__viewed_user_id_user'), 'user', ['user_id'], ['id'], ondelete='cascade')

    with op.batch_alter_table('question__response', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint('fk_question__response_user_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_question__response_user_id_user'), 'user', ['user_id'], ['id'], ondelete='cascade')

    with op.batch_alter_table('result', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint('fk_result_user_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_result_user_id_user'), 'user', ['user_id'], ['id'], ondelete='cascade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_result_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_result_user_id_user', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('question__response', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_question__response_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_question__response_user_id_user', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('content__viewed', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_content__viewed_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_content__viewed_user_id_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
