"""Removed viewed form C_V

Revision ID: ed041c585c72
Revises: b5eb7560c6f4
Create Date: 2021-05-17 16:47:04.400085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed041c585c72'
down_revision = 'b5eb7560c6f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content__viewed', schema=None) as batch_op:
        batch_op.drop_column('viewed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content__viewed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('viewed', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
